# Conda environment for Gammapy user notebooks repository
#
# Install:    conda env create -f environment.yml
# Update:     conda env update -f environment.yml
# Activate:   conda activate gammapy-recipes
# Deactivate: conda deactivate

name: gammapy-recipes

channels:
  - conda-forge
  - sherpa

dependencies:
  # dev dependencies
  - IPython
  - nbformat=5.0.8
  - tqdm
  - click
  - sphinx
  - sphinx-gallery
  - sphinx_rtd_theme
  - nbsphinx
  - black

